### ISSUE TITLE
数据未刷新到UI

### ISSUE THREAD

**Issue by cdslily** [liyaotangLEO/android_live555_rtsp_client#2]
11-12 14:08:49.425 25343 25389 E rtsplive555: FrameType： 67
11-12 14:08:49.446 25343 25389 E rtsplive555: FrameType： 41
11-12 14:08:49.470 25343 25389 E rtsplive555: FrameType： 41
11-12 14:08:49.494 25343 25389 E rtsplive555: FrameType： 41
11-12 14:08:49.517 25343 25389 E rtsplive555: FrameType： 41
打开DummySink::afterGettingFrame中的log
fReceiveBuffer[0]  交替执行以上log，按照您的注释说明，SPS 以及P帧，但从代码逻辑上看，if (fReceiveBuffer[0] == 0x67)  中的代码块将数据拷贝到fReceiveBuffer，但未做ui回显，(fReceiveBuffer[0] == 0x41) 逻辑上未做任何处理，所以在我本地的环境画面是没有任何显示的。
请您帮我分析下该如何处理这个问题。

**Comment by cdslily** [comment]
以下是server的信息
11-12 14:19:55.110 25343 25389 E rtsplive555: FrameType： 41
11-12 14:20:04.213 25437 25475 E rtsplive555: Java_com_rtsp_poe_rtsplive555_RTSPClient_start
11-12 14:20:04.219 25437 25475 E rtsplive555: infoCallBack: to create a RTSP client for URL "rtsp://192.168.88.26:8550/12345":
11-12 14:20:04.562 25437 25475 E rtsplive555: get_sps_pps_from_sdp: sps Z0IAKY2NQDwBE/LNQUCAgeEQinA=
11-12 14:20:04.562 25437 25475 E rtsplive555: get_sps_pps_from_sdp: pps aMpDyA==
11-12 14:20:04.562 25437 25475 E rtsplive555: SDP description： =============================================================
11-12 14:20:04.563 25437 25475 E rtsplive555: infoCallBack: Got a SDP description:
11-12 14:20:04.563 25437 25475 E rtsplive555: v=0
11-12 14:20:04.563 25437 25475 E rtsplive555: o=- 1573539604474393 1 IN IP4 192.168.88.26
11-12 14:20:04.563 25437 25475 E rtsplive555: s=H.264 Video, streamed by the EasyIPCamera v1.3.16.1206
11-12 14:20:04.563 25437 25475 E rtsplive555: i=12345
11-12 14:20:04.563 25437 25475 E rtsplive555: t=0 0
11-12 14:20:04.563 25437 25475 E rtsplive555: a=tool:LIVE555 Streaming Media v2016.04.01
11-12 14:20:04.563 25437 25475 E rtsplive555: a=type:broadcast
11-12 14:20:04.563 25437 25475 E rtsplive555: a=control:*
11-12 14:20:04.563 25437 25475 E rtsplive555: a=range:npt=0-
11-12 14:20:04.563 25437 25475 E rtsplive555: a=x-qt-text-nam:H.264 Video, streamed by the EasyIPCamera v1.3.16.1206
11-12 14:20:04.563 25437 25475 E rtsplive555: a=x-qt-text-inf:12345
11-12 14:20:04.563 25437 25475 E rtsplive555: m=video 0 RTP/AVP 96
11-12 14:20:04.563 25437 25475 E rtsplive555: c=IN IP4 0.0.0.0
11-12 14:20:04.563 25437 25475 E rtsplive555: b=AS:1048576
11-12 14:20:04.563 25437 25475 E rtsplive555: a=rtpmap:96 H264/90000
11-12 14:20:04.563 25437 25475 E rtsplive555: a=fmtp:96 packetization-mode=1;profile-level-id=420029;sprop-parameter-sets=Z0IAKY2NQDwBE/LNQUCAgeEQinA=,aMpDyA==
11-12 14:20:04.563 25437 25475 E rtsplive555: a=control:track1
11-12 14:20:04.569 25437 25475 E rtsplive555: infoCallBack: Initiated the subsession (client port 40976-40977)
11-12 14:20:04.577 25437 25475 E rtsplive555: infoCallBack: Set up the subsession (client port 40976-40977)
11-12 14:20:04.578 25437 25475 E rtsplive555: infoCallBack: Created a data sink for the subsession
11-12 14:20:04.582 25437 25475 E rtsplive555: infoCallBack: Started playing session

**Comment by liyaotangLEO** [comment]
（1）67 是 sps，68 是 pps，sps 和 pps 都传入解码器，再传 p帧才能正常解码
（2）924 行，if (len == 0) 即没从码流中解析出 sps 和 pps，是假设了 sps 和 pps 会同时连续出现，现在看来是码流中只有 sps，没有pps
（3）可以修改一下 924 行这个判断，不使用从码流中解析的 temp_sps_pps，而使用前面通过 sdp 解析出来的 sps_pps_2

**Comment by cdslily** [comment]
好的，非常感谢！ @liyaotangLEO
